### ISSUE TITLE
toTEIXML.js needs work

### ISSUE THREAD

**Issue by hlapin** [umd-mith/mishnah#18]
1. Does not handle word groups (grouped columns)
2. Desideratum: should add pseudo-morph data for post-processing/visualization.

**Comment by raffazizzi** [comment]
Done with 1., 2. was addressing in meeting. closing

**Comment by hlapin** [comment]
toTEIXML.js is again not saving to blob. I can check it against what you had before, but I suspect this is a quicker fix for you.

**Comment by hlapin** [comment]
> toTEIXML.js is again not saving to blob. I can check it against what you had before, but I suspect this is a quicker fix for you.

OK, it appears to be working now. Not sure why it was not.
